---
# This playbook is run from packer during kickstart (phase 1)
- hosts: 127.0.0.1
  user: vagrant
  become: yes

  pre_tasks:
    - include: roles/bbaassssiiee.commoncentos/tasks/stig.yml

  roles:
    - bbaassssiiee.commoncentos
    - RHEL6-STIG
