---
# This playbook is run as a provisioner for vagrant virtual machines
- name: bootstrap centos6 hosts
  hosts: centos6
  gather_facts: True
  become: yes

  roles:
    - bbaassssiiee.commoncentos
    - RHEL6-STIG
