---
# re-use roles from https://galaxy.ansible.com
# to install:
# ansible-galaxy install --force -r requirements.yml

- src: https://github.com/bbaassssiiee/commoncentos.git
  name: bbaassssiiee.commoncentos

- src: https://github.com/MindPointGroup/RHEL6-STIG.git
  name: RHEL6-STIG
  version: molecule
