- hosts: all
  gather_facts: False

  tasks:
    
    - name: "test java"
      shell: java -version
      register: jvm
      changed_when: False
      
    - name: "report"
      debug: msg="Java is {{ jvm }}"
